### PR TITLE
fix(editor): allow user removing data source trait

### PR DESCRIPTION
**Pull request by tanbowensg**

### CODE REVIEW

**Comment by MrWindlike** [comment]
If I remove the datasource trait for a Dummy component, does the schema leave an empty dummy component that cannot be removed on the editor?

**Comment by tanbowensg** [comment]
> If I remove the datasource trait for a Dummy component, does the schema leave an empty dummy component that cannot be removed on the editor?

Yes. It will leave a empty dummy, but you can remove it.

**Comment by MrWindlike** [comment]
When I remove the trait from dummy component, it shows the undefined category in the editor. It might be better to show it as an unknown category.

image

**Comment by tanbowensg** [comment]
OK
截屏2023-01-18 上午11 05 23

**Review by MrWindlike — APPROVED** [review]

**Pull request merged**
